"""fix inbound cita-recepcion relation

Revision ID: 30aa478e8463
Revises: 93f964c0fa86
Create Date: 2025-12-12 21:46:21.142752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30aa478e8463'
down_revision: Union[str, Sequence[str], None] = '93f964c0fa86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inbound_citas_recepcion_id_fkey'), 'inbound_citas', type_='foreignkey')
    op.drop_column('inbound_citas', 'recepcion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_citas', sa.Column('recepcion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inbound_citas_recepcion_id_fkey'), 'inbound_citas', 'inbound_recepciones', ['recepcion_id'], ['id'])
    # ### end Alembic commands ###
