"""agregar tablas inbound del modelo nuevo

Revision ID: 92078e6673dd
Revises: e250b92d36b8
Create Date: 2025-12-09 18:00:24.897257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92078e6673dd'
down_revision: Union[str, Sequence[str], None] = 'e250b92d36b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
