"""inbound segunda version, rutas, servicios y modelos

Revision ID: 93f964c0fa86
Revises: e32c14be8545
Create Date: 2025-12-11 23:08:03.056618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f964c0fa86'
down_revision: Union[str, Sequence[str], None] = 'e32c14be8545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=True),
    sa.Column('transportista', sa.String(length=150), nullable=True),
    sa.Column('patente_camion', sa.String(length=20), nullable=True),
    sa.Column('nombre_conductor', sa.String(length=150), nullable=True),
    sa.Column('fecha_hora_cita', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_llegada_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_citas_creado_por_id'), 'inbound_citas', ['creado_por_id'], unique=False)
    op.create_index(op.f('ix_inbound_citas_fecha_hora_cita'), 'inbound_citas', ['fecha_hora_cita'], unique=False)
    op.create_index(op.f('ix_inbound_citas_id'), 'inbound_citas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_citas_negocio_id'), 'inbound_citas', ['negocio_id'], unique=False)
    op.create_table('inbound_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=False),
    sa.Column('requiere_valor_bool', sa.Boolean(), nullable=False),
    sa.Column('permite_comentario', sa.Boolean(), nullable=False),
    sa.Column('permite_valor_numerico', sa.Boolean(), nullable=False),
    sa.Column('requiere_foto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_checklist_items_id'), 'inbound_checklist_items', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_items_negocio_id'), 'inbound_checklist_items', ['negocio_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=50), nullable=True),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_negocio_id'), 'proveedores', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=False)
    op.create_index(op.f('ix_proveedores_rut'), 'proveedores', ['rut'], unique=False)
    op.create_table('inbound_checklist_respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('valor_bool', sa.Boolean(), nullable=True),
    sa.Column('valor_texto', sa.Text(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('ruta_foto', sa.String(length=500), nullable=True),
    sa.Column('respondido_por_id', sa.Integer(), nullable=True),
    sa.Column('respondido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inbound_checklist_items.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.ForeignKeyConstraint(['respondido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_checklist_respuestas_id'), 'inbound_checklist_respuestas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_item_id'), 'inbound_checklist_respuestas', ['item_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_negocio_id'), 'inbound_checklist_respuestas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_recepcion_id'), 'inbound_checklist_respuestas', ['recepcion_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_respondido_por_id'), 'inbound_checklist_respuestas', ['respondido_por_id'], unique=False)
    op.create_table('inbound_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=False),
    sa.Column('es_validado', sa.Boolean(), nullable=False),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_documentos_id'), 'inbound_documentos', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_documentos_negocio_id'), 'inbound_documentos', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_documentos_recepcion_id'), 'inbound_documentos', ['recepcion_id'], unique=False)
    op.create_table('inbound_firmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre_firmante', sa.String(length=150), nullable=True),
    sa.Column('documento_firmante', sa.String(length=50), nullable=True),
    sa.Column('imagen_path', sa.String(length=255), nullable=False),
    sa.Column('firmado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('firmado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firmado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_firmas_firmado_por_usuario_id'), 'inbound_firmas', ['firmado_por_usuario_id'], unique=False)
    op.create_index(op.f('ix_inbound_firmas_id'), 'inbound_firmas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_firmas_recepcion_id'), 'inbound_firmas', ['recepcion_id'], unique=False)
    op.create_table('inbound_pallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('codigo_pallet', sa.String(length=50), nullable=False),
    sa.Column('peso_bruto_kg', sa.Float(), nullable=True),
    sa.Column('peso_tara_kg', sa.Float(), nullable=True),
    sa.Column('peso_neto_kg', sa.Float(), nullable=True),
    sa.Column('bultos', sa.Integer(), nullable=True),
    sa.Column('temperatura_promedio', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_pallets_codigo_pallet'), 'inbound_pallets', ['codigo_pallet'], unique=False)
    op.create_index(op.f('ix_inbound_pallets_id'), 'inbound_pallets', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_pallets_negocio_id'), 'inbound_pallets', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_pallets_recepcion_id'), 'inbound_pallets', ['recepcion_id'], unique=False)
    op.create_table('inbound_plantillas_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_plantillas_proveedor_id'), 'inbound_plantillas_proveedor', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_proveedor_negocio_id'), 'inbound_plantillas_proveedor', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_proveedor_proveedor_id'), 'inbound_plantillas_proveedor', ['proveedor_id'], unique=False)
    op.create_table('inbound_prealertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('contenedor', sa.String(length=50), nullable=True),
    sa.Column('tipo_carga', sa.String(length=50), nullable=True),
    sa.Column('fecha_estimada_llegada', sa.DateTime(), nullable=True),
    sa.Column('detalle_json', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_prealertas_codigo'), 'inbound_prealertas', ['codigo'], unique=False)
    op.create_index(op.f('ix_inbound_prealertas_id'), 'inbound_prealertas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_prealertas_negocio_id'), 'inbound_prealertas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_prealertas_proveedor_id'), 'inbound_prealertas', ['proveedor_id'], unique=False)
    op.create_table('inbound_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('incidencia_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incidencia_id'], ['inbound_incidencias.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['inbound_lineas.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_fotos_id'), 'inbound_fotos', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_fotos_incidencia_id'), 'inbound_fotos', ['incidencia_id'], unique=False)
    op.create_index(op.f('ix_inbound_fotos_linea_id'), 'inbound_fotos', ['linea_id'], unique=False)
    op.create_index(op.f('ix_inbound_fotos_negocio_id'), 'inbound_fotos', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_fotos_recepcion_id'), 'inbound_fotos', ['recepcion_id'], unique=False)
    op.create_table('inbound_pallet_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['linea_id'], ['inbound_lineas.id'], ),
    sa.ForeignKeyConstraint(['pallet_id'], ['inbound_pallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_pallet_items_id'), 'inbound_pallet_items', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_pallet_items_linea_id'), 'inbound_pallet_items', ['linea_id'], unique=False)
    op.create_index(op.f('ix_inbound_pallet_items_pallet_id'), 'inbound_pallet_items', ['pallet_id'], unique=False)
    op.create_table('inbound_plantillas_proveedor_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_sugerida', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('peso_kg_sugerido', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plantilla_id'], ['inbound_plantillas_proveedor.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_plantillas_proveedor_lineas_id'), 'inbound_plantillas_proveedor_lineas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_proveedor_lineas_plantilla_id'), 'inbound_plantillas_proveedor_lineas', ['plantilla_id'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_proveedor_lineas_producto_id'), 'inbound_plantillas_proveedor_lineas', ['producto_id'], unique=False)
    op.add_column('inbound_incidencias', sa.Column('estado', sa.String(length=20), nullable=False))
    op.add_column('inbound_incidencias', sa.Column('responsable_id', sa.Integer(), nullable=True))
    op.add_column('inbound_incidencias', sa.Column('cerrado_en', sa.DateTime(), nullable=True))
    op.add_column('inbound_incidencias', sa.Column('accion_correctiva', sa.Text(), nullable=True))
    op.add_column('inbound_incidencias', sa.Column('datos_json', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'inbound_incidencias', 'usuarios', ['responsable_id'], ['id'])
    op.add_column('inbound_lineas', sa.Column('temperatura_fuera_rango', sa.Boolean(), nullable=False))
    op.add_column('inbound_recepciones', sa.Column('cita_id', sa.Integer(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('checklist_completado', sa.Boolean(), nullable=False))
    op.add_column('inbound_recepciones', sa.Column('checklist_completado_por_id', sa.Integer(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('checklist_completado_en', sa.DateTime(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('documentacion_completa', sa.Boolean(), nullable=False))
    op.add_column('inbound_recepciones', sa.Column('peso_bruto_kg', sa.Float(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('peso_tara_kg', sa.Float(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('peso_neto_kg', sa.Float(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('peso_diferencia_kg', sa.Float(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('origen_peso', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_inbound_recepciones_cita_id'), 'inbound_recepciones', ['cita_id'], unique=False)
    op.create_foreign_key(None, 'inbound_recepciones', 'usuarios', ['checklist_completado_por_id'], ['id'])
    op.create_foreign_key(None, 'inbound_recepciones', 'inbound_citas', ['cita_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbound_recepciones', type_='foreignkey')
    op.drop_constraint(None, 'inbound_recepciones', type_='foreignkey')
    op.drop_index(op.f('ix_inbound_recepciones_cita_id'), table_name='inbound_recepciones')
    op.drop_column('inbound_recepciones', 'origen_peso')
    op.drop_column('inbound_recepciones', 'peso_diferencia_kg')
    op.drop_column('inbound_recepciones', 'peso_neto_kg')
    op.drop_column('inbound_recepciones', 'peso_tara_kg')
    op.drop_column('inbound_recepciones', 'peso_bruto_kg')
    op.drop_column('inbound_recepciones', 'documentacion_completa')
    op.drop_column('inbound_recepciones', 'checklist_completado_en')
    op.drop_column('inbound_recepciones', 'checklist_completado_por_id')
    op.drop_column('inbound_recepciones', 'checklist_completado')
    op.drop_column('inbound_recepciones', 'cita_id')
    op.drop_column('inbound_lineas', 'temperatura_fuera_rango')
    op.drop_constraint(None, 'inbound_incidencias', type_='foreignkey')
    op.drop_column('inbound_incidencias', 'datos_json')
    op.drop_column('inbound_incidencias', 'accion_correctiva')
    op.drop_column('inbound_incidencias', 'cerrado_en')
    op.drop_column('inbound_incidencias', 'responsable_id')
    op.drop_column('inbound_incidencias', 'estado')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_lineas_producto_id'), table_name='inbound_plantillas_proveedor_lineas')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_lineas_plantilla_id'), table_name='inbound_plantillas_proveedor_lineas')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_lineas_id'), table_name='inbound_plantillas_proveedor_lineas')
    op.drop_table('inbound_plantillas_proveedor_lineas')
    op.drop_index(op.f('ix_inbound_pallet_items_pallet_id'), table_name='inbound_pallet_items')
    op.drop_index(op.f('ix_inbound_pallet_items_linea_id'), table_name='inbound_pallet_items')
    op.drop_index(op.f('ix_inbound_pallet_items_id'), table_name='inbound_pallet_items')
    op.drop_table('inbound_pallet_items')
    op.drop_index(op.f('ix_inbound_fotos_recepcion_id'), table_name='inbound_fotos')
    op.drop_index(op.f('ix_inbound_fotos_negocio_id'), table_name='inbound_fotos')
    op.drop_index(op.f('ix_inbound_fotos_linea_id'), table_name='inbound_fotos')
    op.drop_index(op.f('ix_inbound_fotos_incidencia_id'), table_name='inbound_fotos')
    op.drop_index(op.f('ix_inbound_fotos_id'), table_name='inbound_fotos')
    op.drop_table('inbound_fotos')
    op.drop_index(op.f('ix_inbound_prealertas_proveedor_id'), table_name='inbound_prealertas')
    op.drop_index(op.f('ix_inbound_prealertas_negocio_id'), table_name='inbound_prealertas')
    op.drop_index(op.f('ix_inbound_prealertas_id'), table_name='inbound_prealertas')
    op.drop_index(op.f('ix_inbound_prealertas_codigo'), table_name='inbound_prealertas')
    op.drop_table('inbound_prealertas')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_proveedor_id'), table_name='inbound_plantillas_proveedor')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_negocio_id'), table_name='inbound_plantillas_proveedor')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_id'), table_name='inbound_plantillas_proveedor')
    op.drop_table('inbound_plantillas_proveedor')
    op.drop_index(op.f('ix_inbound_pallets_recepcion_id'), table_name='inbound_pallets')
    op.drop_index(op.f('ix_inbound_pallets_negocio_id'), table_name='inbound_pallets')
    op.drop_index(op.f('ix_inbound_pallets_id'), table_name='inbound_pallets')
    op.drop_index(op.f('ix_inbound_pallets_codigo_pallet'), table_name='inbound_pallets')
    op.drop_table('inbound_pallets')
    op.drop_index(op.f('ix_inbound_firmas_recepcion_id'), table_name='inbound_firmas')
    op.drop_index(op.f('ix_inbound_firmas_id'), table_name='inbound_firmas')
    op.drop_index(op.f('ix_inbound_firmas_firmado_por_usuario_id'), table_name='inbound_firmas')
    op.drop_table('inbound_firmas')
    op.drop_index(op.f('ix_inbound_documentos_recepcion_id'), table_name='inbound_documentos')
    op.drop_index(op.f('ix_inbound_documentos_negocio_id'), table_name='inbound_documentos')
    op.drop_index(op.f('ix_inbound_documentos_id'), table_name='inbound_documentos')
    op.drop_table('inbound_documentos')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_respondido_por_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_recepcion_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_negocio_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_item_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_id'), table_name='inbound_checklist_respuestas')
    op.drop_table('inbound_checklist_respuestas')
    op.drop_index(op.f('ix_proveedores_rut'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_negocio_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_inbound_checklist_items_negocio_id'), table_name='inbound_checklist_items')
    op.drop_index(op.f('ix_inbound_checklist_items_id'), table_name='inbound_checklist_items')
    op.drop_table('inbound_checklist_items')
    op.drop_index(op.f('ix_inbound_citas_negocio_id'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_id'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_fecha_hora_cita'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_creado_por_id'), table_name='inbound_citas')
    op.drop_table('inbound_citas')
    # ### end Alembic commands ###
