"""actualizacion de baseline

Revision ID: a47505a27a27
Revises: 30aa478e8463
Create Date: 2025-12-29 11:35:23.080135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a47505a27a27'
down_revision: Union[str, Sequence[str], None] = '30aa478e8463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suscripciones_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.Enum('INBOUND', 'WMS', name='module_key_enum'), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', 'CANCELLED', name='subscription_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_renewal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('past_due_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Integer(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(current_period_start IS NULL AND current_period_end IS NULL) OR (current_period_end > current_period_start)', name='ck_suscripcion_periodo_valido'),
    sa.CheckConstraint('NOT (trial_ends_at IS NOT NULL AND current_period_start IS NOT NULL)', name='ck_suscripcion_trial_vs_periodo_exclusivo'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'module_key', name='uq_suscripcion_modulo_negocio')
    )
    op.create_index('ix_subs_negocio_status', 'suscripciones_modulo', ['negocio_id', 'status'], unique=False)
    op.create_index('ix_subs_renewal_queue', 'suscripciones_modulo', ['status', 'next_renewal_at'], unique=False)
    op.create_index(op.f('ix_suscripciones_modulo_current_period_end'), 'suscripciones_modulo', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_suscripciones_modulo_current_period_start'), 'suscripciones_modulo', ['current_period_start'], unique=False)
    op.create_index(op.f('ix_suscripciones_modulo_module_key'), 'suscripciones_modulo', ['module_key'], unique=False)
    op.create_index(op.f('ix_suscripciones_modulo_negocio_id'), 'suscripciones_modulo', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_suscripciones_modulo_next_renewal_at'), 'suscripciones_modulo', ['next_renewal_at'], unique=False)
    op.create_index(op.f('ix_suscripciones_modulo_status'), 'suscripciones_modulo', ['status'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.Enum('INBOUND', 'WMS', name='module_key_enum'), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_end > period_start', name='ck_usage_periodo_valido'),
    sa.CheckConstraint('value >= 0', name='ck_usage_value_nonneg'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'module_key', 'metric_key', 'period_start', 'period_end', name='uq_usage_counter_scope')
    )
    op.create_index(op.f('ix_usage_counters_metric_key'), 'usage_counters', ['metric_key'], unique=False)
    op.create_index(op.f('ix_usage_counters_module_key'), 'usage_counters', ['module_key'], unique=False)
    op.create_index(op.f('ix_usage_counters_negocio_id'), 'usage_counters', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_usage_counters_period_end'), 'usage_counters', ['period_end'], unique=False)
    op.create_index(op.f('ix_usage_counters_period_start'), 'usage_counters', ['period_start'], unique=False)
    op.create_index('ix_usage_lookup_current', 'usage_counters', ['negocio_id', 'module_key', 'metric_key', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_usage_negocio_modulo_periodo', 'usage_counters', ['negocio_id', 'module_key', 'period_start', 'period_end'], unique=False)
    op.create_table('inbound_plantillas_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'proveedor_id', 'nombre', name='uq_inb_chk_tpl_neg_prov_nombre')
    )
    op.create_index(op.f('ix_inbound_plantillas_checklist_negocio_id'), 'inbound_plantillas_checklist', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_checklist_nombre'), 'inbound_plantillas_checklist', ['nombre'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_checklist_proveedor_id'), 'inbound_plantillas_checklist', ['proveedor_id'], unique=False)
    op.create_table('inbound_plantillas_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=False),
    sa.Column('opciones', sa.String(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plantilla_id'], ['inbound_plantillas_checklist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plantilla_id', 'codigo', name='uq_inb_chk_item_tpl_codigo')
    )
    op.create_index(op.f('ix_inbound_plantillas_checklist_items_plantilla_id'), 'inbound_plantillas_checklist_items', ['plantilla_id'], unique=False)
    op.create_table('inbound_checklist_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['inbound_plantillas_checklist.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_checklist_recepcion_negocio_id'), 'inbound_checklist_recepcion', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_recepcion_plantilla_id'), 'inbound_checklist_recepcion', ['plantilla_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_recepcion_recepcion_id'), 'inbound_checklist_recepcion', ['recepcion_id'], unique=True)
    op.drop_index(op.f('ix_inbound_firmas_firmado_por_usuario_id'), table_name='inbound_firmas')
    op.drop_index(op.f('ix_inbound_firmas_id'), table_name='inbound_firmas')
    op.drop_index(op.f('ix_inbound_firmas_recepcion_id'), table_name='inbound_firmas')
    op.drop_table('inbound_firmas')
    op.drop_index(op.f('ix_inbound_checklist_items_id'), table_name='inbound_checklist_items')
    op.drop_index(op.f('ix_inbound_checklist_items_negocio_id'), table_name='inbound_checklist_items')
    op.drop_table('inbound_checklist_items')
    op.alter_column('alertas', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('alertas', 'fecha_envio',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('alertas', 'datos_json',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_alertas_fecha_creacion'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.alter_column('auditoria', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('auditoria', 'detalle',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.add_column('inbound_checklist_respuestas', sa.Column('plantilla_id', sa.Integer(), nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('checklist_item_id', sa.Integer(), nullable=False))
    op.add_column('inbound_checklist_respuestas', sa.Column('respondido_por', sa.String(), nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('ok', sa.Boolean(), nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('valor', sa.String(), nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('nota', sa.Text(), nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_checklist_respuestas', sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_inbound_checklist_respuestas_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_item_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_respondido_por_id'), table_name='inbound_checklist_respuestas')
    op.create_index(op.f('ix_inbound_checklist_respuestas_checklist_item_id'), 'inbound_checklist_respuestas', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_creado_en'), 'inbound_checklist_respuestas', ['creado_en'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_plantilla_id'), 'inbound_checklist_respuestas', ['plantilla_id'], unique=False)
    op.create_unique_constraint('uq_inb_chk_resp_recep_item', 'inbound_checklist_respuestas', ['recepcion_id', 'checklist_item_id'])
    op.drop_constraint(op.f('inbound_checklist_respuestas_respondido_por_id_fkey'), 'inbound_checklist_respuestas', type_='foreignkey')
    op.drop_constraint(op.f('inbound_checklist_respuestas_item_id_fkey'), 'inbound_checklist_respuestas', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_checklist_respuestas', 'inbound_plantillas_checklist', ['plantilla_id'], ['id'])
    op.create_foreign_key(None, 'inbound_checklist_respuestas', 'inbound_plantillas_checklist_items', ['checklist_item_id'], ['id'])
    op.drop_column('inbound_checklist_respuestas', 'valor_texto')
    op.drop_column('inbound_checklist_respuestas', 'item_id')
    op.drop_column('inbound_checklist_respuestas', 'respondido_por_id')
    op.drop_column('inbound_checklist_respuestas', 'valor_bool')
    op.drop_column('inbound_checklist_respuestas', 'valor_numerico')
    op.drop_column('inbound_checklist_respuestas', 'ruta_foto')
    op.drop_column('inbound_checklist_respuestas', 'respondido_en')
    op.add_column('inbound_citas', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.add_column('inbound_citas', sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_citas', sa.Column('referencia', sa.String(), nullable=True))
    op.add_column('inbound_citas', sa.Column('notas', sa.String(), nullable=True))
    op.add_column('inbound_citas', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('inbound_citas', 'estado',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PROGRAMADA', 'ARRIBADO', 'RETRASADO', 'CANCELADA', 'COMPLETADA', name='cita_estado'),
               existing_nullable=False)
    op.drop_index(op.f('ix_inbound_citas_creado_por_id'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_fecha_hora_cita'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_id'), table_name='inbound_citas')
    op.create_index(op.f('ix_inbound_citas_fecha_programada'), 'inbound_citas', ['fecha_programada'], unique=False)
    op.create_index(op.f('ix_inbound_citas_proveedor_id'), 'inbound_citas', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_inbound_citas_referencia'), 'inbound_citas', ['referencia'], unique=False)
    op.drop_constraint(op.f('inbound_citas_creado_por_id_fkey'), 'inbound_citas', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_citas', 'proveedores', ['proveedor_id'], ['id'])
    op.drop_column('inbound_citas', 'creado_por_id')
    op.drop_column('inbound_citas', 'creado_en')
    op.drop_column('inbound_citas', 'fecha_hora_llegada_real')
    op.drop_column('inbound_citas', 'nombre_conductor')
    op.drop_column('inbound_citas', 'patente_camion')
    op.drop_column('inbound_citas', 'actualizado_en')
    op.drop_column('inbound_citas', 'observaciones')
    op.drop_column('inbound_citas', 'proveedor')
    op.drop_column('inbound_citas', 'fecha_hora_cita')
    op.drop_column('inbound_citas', 'transportista')
    op.add_column('inbound_config', sa.Column('require_lote', sa.Boolean(), nullable=False))
    op.add_column('inbound_config', sa.Column('require_fecha_vencimiento', sa.Boolean(), nullable=False))
    op.add_column('inbound_config', sa.Column('require_temperatura', sa.Boolean(), nullable=False))
    op.add_column('inbound_config', sa.Column('permitir_editar_en_control_calidad', sa.Boolean(), nullable=False))
    op.add_column('inbound_config', sa.Column('permitir_editar_cerrado', sa.Boolean(), nullable=False))
    op.add_column('inbound_config', sa.Column('reglas_json', sa.Text(), nullable=True))
    op.add_column('inbound_config', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_config', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_inbound_config_id'), table_name='inbound_config')
    op.drop_column('inbound_config', 'creado_en')
    op.drop_column('inbound_config', 'max_incidencias_criticas_por_recepcion')
    op.drop_column('inbound_config', 'sla_total_obj_min')
    op.drop_column('inbound_config', 'habilitar_alertas_incidencias')
    op.drop_column('inbound_config', 'sla_espera_obj_min')
    op.drop_column('inbound_config', 'actualizado_en')
    op.drop_column('inbound_config', 'habilitar_alertas_sla')
    op.drop_column('inbound_config', 'sla_descarga_obj_min')
    op.add_column('inbound_documentos', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('inbound_documentos', sa.Column('uri', sa.String(), nullable=False))
    op.add_column('inbound_documentos', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('inbound_documentos', sa.Column('creado_por', sa.String(), nullable=True))
    op.add_column('inbound_documentos', sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_documentos', sa.Column('activo', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_inbound_documentos_id'), table_name='inbound_documentos')
    op.create_index(op.f('ix_inbound_documentos_activo'), 'inbound_documentos', ['activo'], unique=False)
    op.create_index(op.f('ix_inbound_documentos_creado_en'), 'inbound_documentos', ['creado_en'], unique=False)
    op.drop_constraint(op.f('inbound_documentos_subido_por_id_fkey'), 'inbound_documentos', type_='foreignkey')
    op.drop_column('inbound_documentos', 'es_obligatorio')
    op.drop_column('inbound_documentos', 'subido_por_id')
    op.drop_column('inbound_documentos', 'nombre_archivo')
    op.drop_column('inbound_documentos', 'ruta_archivo')
    op.drop_column('inbound_documentos', 'subido_en')
    op.drop_column('inbound_documentos', 'observaciones')
    op.drop_column('inbound_documentos', 'es_validado')
    op.add_column('inbound_fotos', sa.Column('pallet_id', sa.Integer(), nullable=True))
    op.add_column('inbound_fotos', sa.Column('titulo', sa.String(), nullable=True))
    op.add_column('inbound_fotos', sa.Column('nota', sa.Text(), nullable=True))
    op.add_column('inbound_fotos', sa.Column('archivo_url', sa.String(), nullable=True))
    op.add_column('inbound_fotos', sa.Column('archivo_path', sa.String(), nullable=True))
    op.add_column('inbound_fotos', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('inbound_fotos', sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('inbound_fotos', 'recepcion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_inbound_fotos_id'), table_name='inbound_fotos')
    op.create_index(op.f('ix_inbound_fotos_creado_en'), 'inbound_fotos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_inbound_fotos_pallet_id'), 'inbound_fotos', ['pallet_id'], unique=False)
    op.drop_constraint(op.f('inbound_fotos_subido_por_id_fkey'), 'inbound_fotos', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_fotos', 'inbound_pallets', ['pallet_id'], ['id'])
    op.drop_column('inbound_fotos', 'descripcion')
    op.drop_column('inbound_fotos', 'subido_por_id')
    op.drop_column('inbound_fotos', 'ruta_archivo')
    op.drop_column('inbound_fotos', 'subido_en')
    op.drop_column('inbound_fotos', 'tipo')
    op.add_column('inbound_incidencias', sa.Column('negocio_id', sa.Integer(), nullable=False))
    op.add_column('inbound_incidencias', sa.Column('pallet_id', sa.Integer(), nullable=True))
    op.add_column('inbound_incidencias', sa.Column('titulo', sa.String(), nullable=True))
    op.add_column('inbound_incidencias', sa.Column('detalle', sa.Text(), nullable=True))
    op.add_column('inbound_incidencias', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_inbound_incidencias_id'), table_name='inbound_incidencias')
    op.create_index(op.f('ix_inbound_incidencias_created_at'), 'inbound_incidencias', ['created_at'], unique=False)
    op.create_index(op.f('ix_inbound_incidencias_negocio_id'), 'inbound_incidencias', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_incidencias_pallet_id'), 'inbound_incidencias', ['pallet_id'], unique=False)
    op.create_index(op.f('ix_inbound_incidencias_recepcion_id'), 'inbound_incidencias', ['recepcion_id'], unique=False)
    op.drop_constraint(op.f('inbound_incidencias_creado_por_id_fkey'), 'inbound_incidencias', type_='foreignkey')
    op.drop_constraint(op.f('inbound_incidencias_responsable_id_fkey'), 'inbound_incidencias', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_incidencias', 'inbound_pallets', ['pallet_id'], ['id'])
    op.create_foreign_key(None, 'inbound_incidencias', 'negocios', ['negocio_id'], ['id'])
    op.drop_column('inbound_incidencias', 'datos_json')
    op.drop_column('inbound_incidencias', 'creado_por_id')
    op.drop_column('inbound_incidencias', 'accion_correctiva')
    op.drop_column('inbound_incidencias', 'creado_en')
    op.drop_column('inbound_incidencias', 'descripcion')
    op.drop_column('inbound_incidencias', 'cerrado_en')
    op.drop_column('inbound_incidencias', 'responsable_id')
    op.add_column('inbound_lineas', sa.Column('negocio_id', sa.Integer(), nullable=False))
    op.add_column('inbound_lineas', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('inbound_lineas', sa.Column('cantidad_documento', sa.Float(), nullable=True))
    op.add_column('inbound_lineas', sa.Column('peso_recibido_kg', sa.Float(), nullable=True))
    op.add_column('inbound_lineas', sa.Column('peso_unitario_kg_override', sa.Float(), nullable=True))
    op.add_column('inbound_lineas', sa.Column('unidades_por_bulto_override', sa.Integer(), nullable=True))
    op.add_column('inbound_lineas', sa.Column('peso_por_bulto_kg_override', sa.Float(), nullable=True))
    op.add_column('inbound_lineas', sa.Column('nombre_bulto_override', sa.String(), nullable=True))
    op.alter_column('inbound_lineas', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inbound_lineas', 'fecha_vencimiento',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('inbound_lineas', 'cantidad_recibida',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_inbound_lineas_id'), table_name='inbound_lineas')
    op.create_index(op.f('ix_inbound_lineas_fecha_vencimiento'), 'inbound_lineas', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_inbound_lineas_lote'), 'inbound_lineas', ['lote'], unique=False)
    op.create_index(op.f('ix_inbound_lineas_negocio_id'), 'inbound_lineas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_lineas_producto_id'), 'inbound_lineas', ['producto_id'], unique=False)
    op.create_index(op.f('ix_inbound_lineas_recepcion_id'), 'inbound_lineas', ['recepcion_id'], unique=False)
    op.create_foreign_key(None, 'inbound_lineas', 'negocios', ['negocio_id'], ['id'])
    op.drop_column('inbound_lineas', 'temperatura_fuera_rango')
    op.drop_column('inbound_lineas', 'cantidad_esperada')
    op.add_column('inbound_pallet_items', sa.Column('negocio_id', sa.Integer(), nullable=False))
    op.add_column('inbound_pallet_items', sa.Column('cantidad_estimada', sa.Float(), nullable=True))
    op.add_column('inbound_pallet_items', sa.Column('peso_estimado_kg', sa.Float(), nullable=True))
    op.add_column('inbound_pallet_items', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_inbound_pallet_items_id'), table_name='inbound_pallet_items')
    op.create_index(op.f('ix_inbound_pallet_items_negocio_id'), 'inbound_pallet_items', ['negocio_id'], unique=False)
    op.create_unique_constraint('uq_inbound_palletitem_pallet_linea', 'inbound_pallet_items', ['pallet_id', 'linea_id'])
    op.create_foreign_key(None, 'inbound_pallet_items', 'negocios', ['negocio_id'], ['id'])
    op.add_column('inbound_pallets', sa.Column('estado', sa.Enum('ABIERTO', 'EN_PROCESO', 'LISTO', 'BLOQUEADO', name='pallet_estado'), nullable=False))
    op.add_column('inbound_pallets', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_pallets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_pallets', sa.Column('cerrado_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inbound_pallets', sa.Column('cerrado_por_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_inbound_pallets_id'), table_name='inbound_pallets')
    op.create_index(op.f('ix_inbound_pallets_estado'), 'inbound_pallets', ['estado'], unique=False)
    op.create_unique_constraint('uq_inbound_pallet_codigo', 'inbound_pallets', ['negocio_id', 'recepcion_id', 'codigo_pallet'])
    op.drop_constraint(op.f('inbound_pallets_creado_por_id_fkey'), 'inbound_pallets', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_pallets', 'usuarios', ['cerrado_por_id'], ['id'])
    op.drop_column('inbound_pallets', 'creado_por_id')
    op.drop_column('inbound_pallets', 'creado_en')
    op.add_column('inbound_plantillas_proveedor', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('inbound_plantillas_proveedor', 'activo',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_id'), table_name='inbound_plantillas_proveedor')
    op.create_index(op.f('ix_inbound_plantillas_proveedor_nombre'), 'inbound_plantillas_proveedor', ['nombre'], unique=False)
    op.create_unique_constraint('uq_inbound_plantilla_prov_nombre', 'inbound_plantillas_proveedor', ['negocio_id', 'proveedor_id', 'nombre'])
    op.drop_column('inbound_plantillas_proveedor', 'creado_en')
    op.drop_column('inbound_plantillas_proveedor', 'descripcion')
    op.add_column('inbound_plantillas_proveedor_lineas', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('inbound_plantillas_proveedor_lineas', sa.Column('sku_proveedor', sa.String(), nullable=True))
    op.add_column('inbound_plantillas_proveedor_lineas', sa.Column('ean13', sa.String(), nullable=True))
    op.add_column('inbound_plantillas_proveedor_lineas', sa.Column('activo', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_lineas_id'), table_name='inbound_plantillas_proveedor_lineas')
    op.create_index(op.f('ix_inbound_plantillas_proveedor_lineas_ean13'), 'inbound_plantillas_proveedor_lineas', ['ean13'], unique=False)
    op.create_index(op.f('ix_inbound_plantillas_proveedor_lineas_sku_proveedor'), 'inbound_plantillas_proveedor_lineas', ['sku_proveedor'], unique=False)
    op.create_unique_constraint('uq_inbound_plantilla_linea_producto', 'inbound_plantillas_proveedor_lineas', ['plantilla_id', 'producto_id'])
    op.drop_column('inbound_plantillas_proveedor_lineas', 'peso_kg_sugerido')
    op.drop_column('inbound_plantillas_proveedor_lineas', 'cantidad_sugerida')
    op.add_column('inbound_prealertas', sa.Column('referencia', sa.String(), nullable=True))
    op.add_column('inbound_prealertas', sa.Column('fecha_estimada', sa.Date(), nullable=True))
    op.add_column('inbound_prealertas', sa.Column('datos_json', sa.Text(), nullable=True))
    op.add_column('inbound_prealertas', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_inbound_prealertas_codigo'), table_name='inbound_prealertas')
    op.drop_index(op.f('ix_inbound_prealertas_id'), table_name='inbound_prealertas')
    op.create_index(op.f('ix_inbound_prealertas_estado'), 'inbound_prealertas', ['estado'], unique=False)
    op.create_index(op.f('ix_inbound_prealertas_referencia'), 'inbound_prealertas', ['referencia'], unique=False)
    op.drop_column('inbound_prealertas', 'tipo_carga')
    op.drop_column('inbound_prealertas', 'creado_en')
    op.drop_column('inbound_prealertas', 'codigo')
    op.drop_column('inbound_prealertas', 'detalle_json')
    op.drop_column('inbound_prealertas', 'actualizado_en')
    op.drop_column('inbound_prealertas', 'observaciones')
    op.drop_column('inbound_prealertas', 'fecha_estimada_llegada')
    op.drop_column('inbound_prealertas', 'contenedor')
    op.add_column('inbound_recepciones', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('codigo_recepcion', sa.String(), nullable=False))
    op.add_column('inbound_recepciones', sa.Column('documento_ref', sa.String(), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('fecha_recepcion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inbound_recepciones', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_recepciones', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inbound_recepciones', sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('inbound_recepciones', 'fecha_estimada_llegada',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('inbound_recepciones', 'estado',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PRE_REGISTRADO', 'EN_ESPERA', 'EN_DESCARGA', 'EN_CONTROL_CALIDAD', 'CERRADO', name='recepcion_estado'),
               existing_nullable=False)
    op.alter_column('inbound_recepciones', 'fecha_arribo',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('inbound_recepciones', 'fecha_inicio_descarga',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('inbound_recepciones', 'fecha_fin_descarga',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_inbound_recepciones_codigo'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_id'), table_name='inbound_recepciones')
    op.create_index(op.f('ix_inbound_recepciones_codigo_recepcion'), 'inbound_recepciones', ['codigo_recepcion'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_contenedor'), 'inbound_recepciones', ['contenedor'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_documento_ref'), 'inbound_recepciones', ['documento_ref'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_estado'), 'inbound_recepciones', ['estado'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_fecha_arribo'), 'inbound_recepciones', ['fecha_arribo'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_fecha_cierre'), 'inbound_recepciones', ['fecha_cierre'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_fecha_estimada_llegada'), 'inbound_recepciones', ['fecha_estimada_llegada'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_fecha_fin_descarga'), 'inbound_recepciones', ['fecha_fin_descarga'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_fecha_inicio_descarga'), 'inbound_recepciones', ['fecha_inicio_descarga'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_fecha_recepcion'), 'inbound_recepciones', ['fecha_recepcion'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_negocio_id'), 'inbound_recepciones', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_patente_camion'), 'inbound_recepciones', ['patente_camion'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_proveedor_id'), 'inbound_recepciones', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_tipo_carga'), 'inbound_recepciones', ['tipo_carga'], unique=False)
    op.create_unique_constraint('uq_inbound_recepcion_codigo', 'inbound_recepciones', ['negocio_id', 'codigo_recepcion'])
    op.drop_constraint(op.f('inbound_recepciones_checklist_completado_por_id_fkey'), 'inbound_recepciones', type_='foreignkey')
    op.drop_constraint(op.f('inbound_recepciones_creado_por_id_fkey'), 'inbound_recepciones', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_recepciones', 'proveedores', ['proveedor_id'], ['id'])
    op.drop_column('inbound_recepciones', 'documentacion_completa')
    op.drop_column('inbound_recepciones', 'creado_por_id')
    op.drop_column('inbound_recepciones', 'creado_en')
    op.drop_column('inbound_recepciones', 'codigo')
    op.drop_column('inbound_recepciones', 'checklist_completado_por_id')
    op.drop_column('inbound_recepciones', 'peso_tara_kg')
    op.drop_column('inbound_recepciones', 'checklist_completado')
    op.drop_column('inbound_recepciones', 'peso_bruto_kg')
    op.drop_column('inbound_recepciones', 'referencia_externa')
    op.drop_column('inbound_recepciones', 'peso_diferencia_kg')
    op.drop_column('inbound_recepciones', 'peso_neto_kg')
    op.drop_column('inbound_recepciones', 'origen_peso')
    op.drop_column('inbound_recepciones', 'actualizado_en')
    op.drop_column('inbound_recepciones', 'checklist_completado_en')
    op.drop_column('inbound_recepciones', 'proveedor')
    op.alter_column('movimientos', 'cantidad',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('movimientos', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.add_column('negocios', sa.Column('tenant_type', sa.Enum('CUSTOMER', 'SYSTEM', name='negocio_tenant_type'), nullable=False))
    op.add_column('negocios', sa.Column('entitlements', sa.JSON(), nullable=False))
    op.add_column('negocios', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('negocios', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('negocios', 'estado',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVO', 'SUSPENDIDO', 'BLOQUEADO', name='negocio_estado'),
               existing_nullable=False)
    op.alter_column('negocios', 'ultimo_acceso',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_negocios_id'), table_name='negocios')
    op.create_index(op.f('ix_negocios_tenant_type'), 'negocios', ['tenant_type'], unique=False)
    op.add_column('productos', sa.Column('peso_unitario_kg', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('unidades_por_bulto', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('peso_por_bulto_kg', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('nombre_bulto', sa.String(), nullable=True))
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.add_column('proveedores', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('proveedores', 'activo',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_column('proveedores', 'creado_en')
    op.drop_column('proveedores', 'contacto')
    op.drop_column('proveedores', 'direccion')
    op.drop_column('proveedores', 'actualizado_en')
    op.drop_column('proveedores', 'observaciones')
    op.alter_column('sesiones_usuario', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sesiones_usuario', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones_usuario')
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.drop_index(op.f('ix_ubicaciones_sigla'), table_name='ubicaciones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_zonas_id'), table_name='zonas')
    op.drop_index(op.f('ix_zonas_sigla'), table_name='zonas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_zonas_sigla'), 'zonas', ['sigla'], unique=False)
    op.create_index(op.f('ix_zonas_id'), 'zonas', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_ubicaciones_sigla'), 'ubicaciones', ['sigla'], unique=False)
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones_usuario', ['id'], unique=False)
    op.alter_column('sesiones_usuario', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sesiones_usuario', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('proveedores', sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('proveedores', sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('contacto', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.alter_column('proveedores', 'activo',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('proveedores', 'created_at')
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.drop_column('productos', 'nombre_bulto')
    op.drop_column('productos', 'peso_por_bulto_kg')
    op.drop_column('productos', 'unidades_por_bulto')
    op.drop_column('productos', 'peso_unitario_kg')
    op.drop_index(op.f('ix_negocios_tenant_type'), table_name='negocios')
    op.create_index(op.f('ix_negocios_id'), 'negocios', ['id'], unique=False)
    op.alter_column('negocios', 'ultimo_acceso',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('negocios', 'estado',
               existing_type=sa.Enum('ACTIVO', 'SUSPENDIDO', 'BLOQUEADO', name='negocio_estado'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('negocios', 'updated_at')
    op.drop_column('negocios', 'created_at')
    op.drop_column('negocios', 'entitlements')
    op.drop_column('negocios', 'tenant_type')
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    op.alter_column('movimientos', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('movimientos', 'cantidad',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('inbound_recepciones', sa.Column('proveedor', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('inbound_recepciones', sa.Column('checklist_completado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_recepciones', sa.Column('origen_peso', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('peso_neto_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('peso_diferencia_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('referencia_externa', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('peso_bruto_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('checklist_completado', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('inbound_recepciones', sa.Column('peso_tara_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('checklist_completado_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('inbound_recepciones', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_recepciones', sa.Column('creado_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_recepciones', sa.Column('documentacion_completa', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inbound_recepciones', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_recepciones_creado_por_id_fkey'), 'inbound_recepciones', 'usuarios', ['creado_por_id'], ['id'])
    op.create_foreign_key(op.f('inbound_recepciones_checklist_completado_por_id_fkey'), 'inbound_recepciones', 'usuarios', ['checklist_completado_por_id'], ['id'])
    op.drop_constraint('uq_inbound_recepcion_codigo', 'inbound_recepciones', type_='unique')
    op.drop_index(op.f('ix_inbound_recepciones_tipo_carga'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_proveedor_id'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_patente_camion'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_negocio_id'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_fecha_recepcion'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_fecha_inicio_descarga'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_fecha_fin_descarga'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_fecha_estimada_llegada'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_fecha_cierre'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_fecha_arribo'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_estado'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_documento_ref'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_contenedor'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_codigo_recepcion'), table_name='inbound_recepciones')
    op.create_index(op.f('ix_inbound_recepciones_id'), 'inbound_recepciones', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_recepciones_codigo'), 'inbound_recepciones', ['codigo'], unique=True)
    op.alter_column('inbound_recepciones', 'fecha_fin_descarga',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inbound_recepciones', 'fecha_inicio_descarga',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inbound_recepciones', 'fecha_arribo',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inbound_recepciones', 'estado',
               existing_type=sa.Enum('PRE_REGISTRADO', 'EN_ESPERA', 'EN_DESCARGA', 'EN_CONTROL_CALIDAD', 'CERRADO', name='recepcion_estado'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('inbound_recepciones', 'fecha_estimada_llegada',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('inbound_recepciones', 'fecha_cierre')
    op.drop_column('inbound_recepciones', 'updated_at')
    op.drop_column('inbound_recepciones', 'created_at')
    op.drop_column('inbound_recepciones', 'fecha_recepcion')
    op.drop_column('inbound_recepciones', 'documento_ref')
    op.drop_column('inbound_recepciones', 'codigo_recepcion')
    op.drop_column('inbound_recepciones', 'proveedor_id')
    op.add_column('inbound_prealertas', sa.Column('contenedor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inbound_prealertas', sa.Column('fecha_estimada_llegada', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('inbound_prealertas', sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inbound_prealertas', sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_prealertas', sa.Column('detalle_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inbound_prealertas', sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('inbound_prealertas', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_prealertas', sa.Column('tipo_carga', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_inbound_prealertas_referencia'), table_name='inbound_prealertas')
    op.drop_index(op.f('ix_inbound_prealertas_estado'), table_name='inbound_prealertas')
    op.create_index(op.f('ix_inbound_prealertas_id'), 'inbound_prealertas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_prealertas_codigo'), 'inbound_prealertas', ['codigo'], unique=False)
    op.drop_column('inbound_prealertas', 'created_at')
    op.drop_column('inbound_prealertas', 'datos_json')
    op.drop_column('inbound_prealertas', 'fecha_estimada')
    op.drop_column('inbound_prealertas', 'referencia')
    op.add_column('inbound_plantillas_proveedor_lineas', sa.Column('cantidad_sugerida', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_plantillas_proveedor_lineas', sa.Column('peso_kg_sugerido', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_inbound_plantilla_linea_producto', 'inbound_plantillas_proveedor_lineas', type_='unique')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_lineas_sku_proveedor'), table_name='inbound_plantillas_proveedor_lineas')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_lineas_ean13'), table_name='inbound_plantillas_proveedor_lineas')
    op.create_index(op.f('ix_inbound_plantillas_proveedor_lineas_id'), 'inbound_plantillas_proveedor_lineas', ['id'], unique=False)
    op.drop_column('inbound_plantillas_proveedor_lineas', 'activo')
    op.drop_column('inbound_plantillas_proveedor_lineas', 'ean13')
    op.drop_column('inbound_plantillas_proveedor_lineas', 'sku_proveedor')
    op.drop_column('inbound_plantillas_proveedor_lineas', 'descripcion')
    op.add_column('inbound_plantillas_proveedor', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inbound_plantillas_proveedor', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_inbound_plantilla_prov_nombre', 'inbound_plantillas_proveedor', type_='unique')
    op.drop_index(op.f('ix_inbound_plantillas_proveedor_nombre'), table_name='inbound_plantillas_proveedor')
    op.create_index(op.f('ix_inbound_plantillas_proveedor_id'), 'inbound_plantillas_proveedor', ['id'], unique=False)
    op.alter_column('inbound_plantillas_proveedor', 'activo',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('inbound_plantillas_proveedor', 'created_at')
    op.add_column('inbound_pallets', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_pallets', sa.Column('creado_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_pallets', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_pallets_creado_por_id_fkey'), 'inbound_pallets', 'usuarios', ['creado_por_id'], ['id'])
    op.drop_constraint('uq_inbound_pallet_codigo', 'inbound_pallets', type_='unique')
    op.drop_index(op.f('ix_inbound_pallets_estado'), table_name='inbound_pallets')
    op.create_index(op.f('ix_inbound_pallets_id'), 'inbound_pallets', ['id'], unique=False)
    op.drop_column('inbound_pallets', 'cerrado_por_id')
    op.drop_column('inbound_pallets', 'cerrado_at')
    op.drop_column('inbound_pallets', 'updated_at')
    op.drop_column('inbound_pallets', 'created_at')
    op.drop_column('inbound_pallets', 'estado')
    op.drop_constraint(None, 'inbound_pallet_items', type_='foreignkey')
    op.drop_constraint('uq_inbound_palletitem_pallet_linea', 'inbound_pallet_items', type_='unique')
    op.drop_index(op.f('ix_inbound_pallet_items_negocio_id'), table_name='inbound_pallet_items')
    op.create_index(op.f('ix_inbound_pallet_items_id'), 'inbound_pallet_items', ['id'], unique=False)
    op.drop_column('inbound_pallet_items', 'created_at')
    op.drop_column('inbound_pallet_items', 'peso_estimado_kg')
    op.drop_column('inbound_pallet_items', 'cantidad_estimada')
    op.drop_column('inbound_pallet_items', 'negocio_id')
    op.add_column('inbound_lineas', sa.Column('cantidad_esperada', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_lineas', sa.Column('temperatura_fuera_rango', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inbound_lineas', type_='foreignkey')
    op.drop_index(op.f('ix_inbound_lineas_recepcion_id'), table_name='inbound_lineas')
    op.drop_index(op.f('ix_inbound_lineas_producto_id'), table_name='inbound_lineas')
    op.drop_index(op.f('ix_inbound_lineas_negocio_id'), table_name='inbound_lineas')
    op.drop_index(op.f('ix_inbound_lineas_lote'), table_name='inbound_lineas')
    op.drop_index(op.f('ix_inbound_lineas_fecha_vencimiento'), table_name='inbound_lineas')
    op.create_index(op.f('ix_inbound_lineas_id'), 'inbound_lineas', ['id'], unique=False)
    op.alter_column('inbound_lineas', 'cantidad_recibida',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('inbound_lineas', 'fecha_vencimiento',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inbound_lineas', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inbound_lineas', 'nombre_bulto_override')
    op.drop_column('inbound_lineas', 'peso_por_bulto_kg_override')
    op.drop_column('inbound_lineas', 'unidades_por_bulto_override')
    op.drop_column('inbound_lineas', 'peso_unitario_kg_override')
    op.drop_column('inbound_lineas', 'peso_recibido_kg')
    op.drop_column('inbound_lineas', 'cantidad_documento')
    op.drop_column('inbound_lineas', 'descripcion')
    op.drop_column('inbound_lineas', 'negocio_id')
    op.add_column('inbound_incidencias', sa.Column('responsable_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_incidencias', sa.Column('cerrado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('inbound_incidencias', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('inbound_incidencias', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_incidencias', sa.Column('accion_correctiva', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inbound_incidencias', sa.Column('creado_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_incidencias', sa.Column('datos_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_incidencias', type_='foreignkey')
    op.drop_constraint(None, 'inbound_incidencias', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_incidencias_responsable_id_fkey'), 'inbound_incidencias', 'usuarios', ['responsable_id'], ['id'])
    op.create_foreign_key(op.f('inbound_incidencias_creado_por_id_fkey'), 'inbound_incidencias', 'usuarios', ['creado_por_id'], ['id'])
    op.drop_index(op.f('ix_inbound_incidencias_recepcion_id'), table_name='inbound_incidencias')
    op.drop_index(op.f('ix_inbound_incidencias_pallet_id'), table_name='inbound_incidencias')
    op.drop_index(op.f('ix_inbound_incidencias_negocio_id'), table_name='inbound_incidencias')
    op.drop_index(op.f('ix_inbound_incidencias_created_at'), table_name='inbound_incidencias')
    op.create_index(op.f('ix_inbound_incidencias_id'), 'inbound_incidencias', ['id'], unique=False)
    op.drop_column('inbound_incidencias', 'created_at')
    op.drop_column('inbound_incidencias', 'detalle')
    op.drop_column('inbound_incidencias', 'titulo')
    op.drop_column('inbound_incidencias', 'pallet_id')
    op.drop_column('inbound_incidencias', 'negocio_id')
    op.add_column('inbound_fotos', sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inbound_fotos', sa.Column('subido_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_fotos', sa.Column('ruta_archivo', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('inbound_fotos', sa.Column('subido_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_fotos', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_fotos', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_fotos_subido_por_id_fkey'), 'inbound_fotos', 'usuarios', ['subido_por_id'], ['id'])
    op.drop_index(op.f('ix_inbound_fotos_pallet_id'), table_name='inbound_fotos')
    op.drop_index(op.f('ix_inbound_fotos_creado_en'), table_name='inbound_fotos')
    op.create_index(op.f('ix_inbound_fotos_id'), 'inbound_fotos', ['id'], unique=False)
    op.alter_column('inbound_fotos', 'recepcion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inbound_fotos', 'creado_en')
    op.drop_column('inbound_fotos', 'size_bytes')
    op.drop_column('inbound_fotos', 'archivo_path')
    op.drop_column('inbound_fotos', 'archivo_url')
    op.drop_column('inbound_fotos', 'nota')
    op.drop_column('inbound_fotos', 'titulo')
    op.drop_column('inbound_fotos', 'pallet_id')
    op.add_column('inbound_documentos', sa.Column('es_validado', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('inbound_documentos', sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inbound_documentos', sa.Column('subido_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_documentos', sa.Column('ruta_archivo', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('inbound_documentos', sa.Column('nombre_archivo', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('inbound_documentos', sa.Column('subido_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_documentos', sa.Column('es_obligatorio', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('inbound_documentos_subido_por_id_fkey'), 'inbound_documentos', 'usuarios', ['subido_por_id'], ['id'])
    op.drop_index(op.f('ix_inbound_documentos_creado_en'), table_name='inbound_documentos')
    op.drop_index(op.f('ix_inbound_documentos_activo'), table_name='inbound_documentos')
    op.create_index(op.f('ix_inbound_documentos_id'), 'inbound_documentos', ['id'], unique=False)
    op.drop_column('inbound_documentos', 'activo')
    op.drop_column('inbound_documentos', 'creado_en')
    op.drop_column('inbound_documentos', 'creado_por')
    op.drop_column('inbound_documentos', 'descripcion')
    op.drop_column('inbound_documentos', 'uri')
    op.drop_column('inbound_documentos', 'nombre')
    op.add_column('inbound_config', sa.Column('sla_descarga_obj_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_config', sa.Column('habilitar_alertas_sla', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('inbound_config', sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_config', sa.Column('sla_espera_obj_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_config', sa.Column('habilitar_alertas_incidencias', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('inbound_config', sa.Column('sla_total_obj_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_config', sa.Column('max_incidencias_criticas_por_recepcion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_config', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_inbound_config_id'), 'inbound_config', ['id'], unique=False)
    op.drop_column('inbound_config', 'updated_at')
    op.drop_column('inbound_config', 'created_at')
    op.drop_column('inbound_config', 'reglas_json')
    op.drop_column('inbound_config', 'permitir_editar_cerrado')
    op.drop_column('inbound_config', 'permitir_editar_en_control_calidad')
    op.drop_column('inbound_config', 'require_temperatura')
    op.drop_column('inbound_config', 'require_fecha_vencimiento')
    op.drop_column('inbound_config', 'require_lote')
    op.add_column('inbound_citas', sa.Column('transportista', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('inbound_citas', sa.Column('fecha_hora_cita', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_citas', sa.Column('proveedor', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('inbound_citas', sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('inbound_citas', sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_citas', sa.Column('patente_camion', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('inbound_citas', sa.Column('nombre_conductor', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('inbound_citas', sa.Column('fecha_hora_llegada_real', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('inbound_citas', sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_citas', sa.Column('creado_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_citas', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_citas_creado_por_id_fkey'), 'inbound_citas', 'usuarios', ['creado_por_id'], ['id'])
    op.drop_index(op.f('ix_inbound_citas_referencia'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_proveedor_id'), table_name='inbound_citas')
    op.drop_index(op.f('ix_inbound_citas_fecha_programada'), table_name='inbound_citas')
    op.create_index(op.f('ix_inbound_citas_id'), 'inbound_citas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_citas_fecha_hora_cita'), 'inbound_citas', ['fecha_hora_cita'], unique=False)
    op.create_index(op.f('ix_inbound_citas_creado_por_id'), 'inbound_citas', ['creado_por_id'], unique=False)
    op.alter_column('inbound_citas', 'estado',
               existing_type=sa.Enum('PROGRAMADA', 'ARRIBADO', 'RETRASADO', 'CANCELADA', 'COMPLETADA', name='cita_estado'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('inbound_citas', 'created_at')
    op.drop_column('inbound_citas', 'notas')
    op.drop_column('inbound_citas', 'referencia')
    op.drop_column('inbound_citas', 'fecha_programada')
    op.drop_column('inbound_citas', 'proveedor_id')
    op.add_column('inbound_checklist_respuestas', sa.Column('respondido_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('inbound_checklist_respuestas', sa.Column('ruta_foto', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('valor_numerico', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('valor_bool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('respondido_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_checklist_respuestas', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inbound_checklist_respuestas', sa.Column('valor_texto', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_checklist_respuestas', type_='foreignkey')
    op.drop_constraint(None, 'inbound_checklist_respuestas', type_='foreignkey')
    op.create_foreign_key(op.f('inbound_checklist_respuestas_item_id_fkey'), 'inbound_checklist_respuestas', 'inbound_checklist_items', ['item_id'], ['id'])
    op.create_foreign_key(op.f('inbound_checklist_respuestas_respondido_por_id_fkey'), 'inbound_checklist_respuestas', 'usuarios', ['respondido_por_id'], ['id'])
    op.drop_constraint('uq_inb_chk_resp_recep_item', 'inbound_checklist_respuestas', type_='unique')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_plantilla_id'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_creado_en'), table_name='inbound_checklist_respuestas')
    op.drop_index(op.f('ix_inbound_checklist_respuestas_checklist_item_id'), table_name='inbound_checklist_respuestas')
    op.create_index(op.f('ix_inbound_checklist_respuestas_respondido_por_id'), 'inbound_checklist_respuestas', ['respondido_por_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_item_id'), 'inbound_checklist_respuestas', ['item_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_respuestas_id'), 'inbound_checklist_respuestas', ['id'], unique=False)
    op.drop_column('inbound_checklist_respuestas', 'actualizado_en')
    op.drop_column('inbound_checklist_respuestas', 'creado_en')
    op.drop_column('inbound_checklist_respuestas', 'nota')
    op.drop_column('inbound_checklist_respuestas', 'valor')
    op.drop_column('inbound_checklist_respuestas', 'ok')
    op.drop_column('inbound_checklist_respuestas', 'respondido_por')
    op.drop_column('inbound_checklist_respuestas', 'checklist_item_id')
    op.drop_column('inbound_checklist_respuestas', 'plantilla_id')
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    op.alter_column('auditoria', 'detalle',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('auditoria', 'fecha',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_fecha_creacion'), 'alertas', ['fecha_creacion'], unique=False)
    op.alter_column('alertas', 'datos_json',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('alertas', 'fecha_envio',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('alertas', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('inbound_checklist_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('texto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('es_obligatorio', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('requiere_valor_bool', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('permite_comentario', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('permite_valor_numerico', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('requiere_foto', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], name=op.f('inbound_checklist_items_negocio_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inbound_checklist_items_pkey'))
    )
    op.create_index(op.f('ix_inbound_checklist_items_negocio_id'), 'inbound_checklist_items', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_inbound_checklist_items_id'), 'inbound_checklist_items', ['id'], unique=False)
    op.create_table('inbound_firmas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recepcion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('nombre_firmante', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('documento_firmante', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('imagen_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('firmado_por_usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firmado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['firmado_por_usuario_id'], ['usuarios.id'], name=op.f('inbound_firmas_firmado_por_usuario_id_fkey')),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], name=op.f('inbound_firmas_recepcion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inbound_firmas_pkey'))
    )
    op.create_index(op.f('ix_inbound_firmas_recepcion_id'), 'inbound_firmas', ['recepcion_id'], unique=False)
    op.create_index(op.f('ix_inbound_firmas_id'), 'inbound_firmas', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_firmas_firmado_por_usuario_id'), 'inbound_firmas', ['firmado_por_usuario_id'], unique=False)
    op.drop_index(op.f('ix_inbound_checklist_recepcion_recepcion_id'), table_name='inbound_checklist_recepcion')
    op.drop_index(op.f('ix_inbound_checklist_recepcion_plantilla_id'), table_name='inbound_checklist_recepcion')
    op.drop_index(op.f('ix_inbound_checklist_recepcion_negocio_id'), table_name='inbound_checklist_recepcion')
    op.drop_table('inbound_checklist_recepcion')
    op.drop_index(op.f('ix_inbound_plantillas_checklist_items_plantilla_id'), table_name='inbound_plantillas_checklist_items')
    op.drop_table('inbound_plantillas_checklist_items')
    op.drop_index(op.f('ix_inbound_plantillas_checklist_proveedor_id'), table_name='inbound_plantillas_checklist')
    op.drop_index(op.f('ix_inbound_plantillas_checklist_nombre'), table_name='inbound_plantillas_checklist')
    op.drop_index(op.f('ix_inbound_plantillas_checklist_negocio_id'), table_name='inbound_plantillas_checklist')
    op.drop_table('inbound_plantillas_checklist')
    op.drop_index('ix_usage_negocio_modulo_periodo', table_name='usage_counters')
    op.drop_index('ix_usage_lookup_current', table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_period_start'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_period_end'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_negocio_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_module_key'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_counters_metric_key'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_suscripciones_modulo_status'), table_name='suscripciones_modulo')
    op.drop_index(op.f('ix_suscripciones_modulo_next_renewal_at'), table_name='suscripciones_modulo')
    op.drop_index(op.f('ix_suscripciones_modulo_negocio_id'), table_name='suscripciones_modulo')
    op.drop_index(op.f('ix_suscripciones_modulo_module_key'), table_name='suscripciones_modulo')
    op.drop_index(op.f('ix_suscripciones_modulo_current_period_start'), table_name='suscripciones_modulo')
    op.drop_index(op.f('ix_suscripciones_modulo_current_period_end'), table_name='suscripciones_modulo')
    op.drop_index('ix_subs_renewal_queue', table_name='suscripciones_modulo')
    op.drop_index('ix_subs_negocio_status', table_name='suscripciones_modulo')
    op.drop_table('suscripciones_modulo')
    # ### end Alembic commands ###
