"""agregar sku/ean en entradas y movimientos

Revision ID: e250b92d36b8
Revises: 58de9d4266c7
Create Date: 2025-12-04 22:15:21.943498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e250b92d36b8'
down_revision: Union[str, Sequence[str], None] = '58de9d4266c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos', sa.Column('codigo_producto', sa.String(), nullable=True))
    op.create_index(op.f('ix_movimientos_codigo_producto'), 'movimientos', ['codigo_producto'], unique=False)
    op.add_column('productos', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('productos', sa.Column('ean13', sa.String(), nullable=True))
    op.create_index(op.f('ix_productos_ean13'), 'productos', ['ean13'], unique=False)
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_index(op.f('ix_productos_ean13'), table_name='productos')
    op.drop_column('productos', 'ean13')
    op.drop_column('productos', 'sku')
    op.drop_index(op.f('ix_movimientos_codigo_producto'), table_name='movimientos')
    op.drop_column('movimientos', 'codigo_producto')
    # ### end Alembic commands ###
