"""modelos inbound

Revision ID: e32c14be8545
Revises: 92078e6673dd
Create Date: 2025-12-11 22:02:55.651313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32c14be8545'
down_revision: Union[str, Sequence[str], None] = '92078e6673dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('sla_espera_obj_min', sa.Float(), nullable=True),
    sa.Column('sla_descarga_obj_min', sa.Float(), nullable=True),
    sa.Column('sla_total_obj_min', sa.Float(), nullable=True),
    sa.Column('max_incidencias_criticas_por_recepcion', sa.Integer(), nullable=True),
    sa.Column('habilitar_alertas_sla', sa.Boolean(), nullable=False),
    sa.Column('habilitar_alertas_incidencias', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_config_id'), 'inbound_config', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_config_negocio_id'), 'inbound_config', ['negocio_id'], unique=True)
    op.create_table('inbound_recepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('proveedor', sa.String(length=150), nullable=False),
    sa.Column('referencia_externa', sa.String(length=150), nullable=True),
    sa.Column('contenedor', sa.String(length=50), nullable=True),
    sa.Column('patente_camion', sa.String(length=20), nullable=True),
    sa.Column('tipo_carga', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_estimada_llegada', sa.DateTime(), nullable=True),
    sa.Column('fecha_arribo', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio_descarga', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_descarga', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_recepciones_codigo'), 'inbound_recepciones', ['codigo'], unique=True)
    op.create_index(op.f('ix_inbound_recepciones_id'), 'inbound_recepciones', ['id'], unique=False)
    op.create_table('inbound_incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criticidad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_incidencias_id'), 'inbound_incidencias', ['id'], unique=False)
    op.create_table('inbound_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('cantidad_esperada', sa.Float(), nullable=True),
    sa.Column('cantidad_recibida', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('temperatura_objetivo', sa.Float(), nullable=True),
    sa.Column('temperatura_recibida', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('bultos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['inbound_recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_lineas_id'), 'inbound_lineas', ['id'], unique=False)
    op.add_column('productos', sa.Column('origen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'origen')
    op.drop_index(op.f('ix_inbound_lineas_id'), table_name='inbound_lineas')
    op.drop_table('inbound_lineas')
    op.drop_index(op.f('ix_inbound_incidencias_id'), table_name='inbound_incidencias')
    op.drop_table('inbound_incidencias')
    op.drop_index(op.f('ix_inbound_recepciones_id'), table_name='inbound_recepciones')
    op.drop_index(op.f('ix_inbound_recepciones_codigo'), table_name='inbound_recepciones')
    op.drop_table('inbound_recepciones')
    op.drop_index(op.f('ix_inbound_config_negocio_id'), table_name='inbound_config')
    op.drop_index(op.f('ix_inbound_config_id'), table_name='inbound_config')
    op.drop_table('inbound_config')
    # ### end Alembic commands ###
